# -*- coding: utf-8 -*-
"""qb and qp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAkvGKHFLUHu-tIEWyV15GY6f914oNpy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


df = pd.read_csv("salton_sea.csv")

df = df[['Year','SeaVolume_m3','SeaSalinity_kg_m3','Qb_m3','Qp_m3']]
df = df.dropna()

volume = df['SeaVolume_m3'].values
salinity = df['SeaSalinity_kg_m3'].values
qb = df['Qb_m3'].values
qp = df['Qp_m3'].values


X = np.column_stack((volume, salinity))
y = np.column_stack((qb, qp))

x_scaler = StandardScaler()
y_scaler = StandardScaler()

X_scaled = x_scaler.fit_transform(X)
y_scaled = y_scaler.fit_transform(y)

model = Sequential([
    Dense(32, activation='relu', input_shape=(2,)),
    Dense(16, activation='relu'),
    Dense(2)
])

model.compile(optimizer='adam', loss='mse')
model.fit(X_scaled, y_scaled, epochs=300, verbose=0)

print("Neural network trained.")




lambda_decay = 0.18


initial_V = volume[-1]
initial_S = salinity[-1]

V_target = 1.114 * initial_V
S_target = 0.8144 * initial_S

current_V = initial_V
current_S = initial_S
last_year = int(df['Year'].iloc[-1])

forecast_years = 10

forecast_qb = []
forecast_qp = []
forecast_V  = []
forecast_S  = []



for i in range(forecast_years):

    X_input = np.array([[current_V, current_S]])
    X_input_scaled = x_scaler.transform(X_input)

    prediction_scaled = model.predict(X_input_scaled, verbose=0)
    prediction = y_scaler.inverse_transform(prediction_scaled)

    next_qb, next_qp = prediction[0]


    next_V = current_V + lambda_decay * (V_target - current_V)
    next_S = current_S + lambda_decay * (S_target - current_S)

    forecast_qb.append(next_qb)
    forecast_qp.append(next_qp)
    forecast_V.append(next_V)
    forecast_S.append(next_S)

    current_V = next_V
    current_S = next_S



future_years = np.arange(last_year+1, last_year+1+forecast_years)

plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
plt.plot(df['Year'], qb, label='Historical')
plt.plot(future_years, forecast_qb, '--', label='Forecast')
plt.title("Qb")
plt.legend()

plt.subplot(2,2,2)
plt.plot(df['Year'], qp, label='Historical')
plt.plot(future_years, forecast_qp, '--', label='Forecast')
plt.title("Qp")
plt.legend()

plt.subplot(2,2,3)
plt.plot(df['Year'], volume, label='Historical')
plt.plot(future_years, forecast_V, '--', label='Forecast')
plt.title("Volume (Converging)")
plt.legend()

plt.subplot(2,2,4)
plt.plot(df['Year'], salinity, label='Historical')
plt.plot(future_years, forecast_S, '--', label='Forecast')
plt.title("Salinity (Converging)")
plt.legend()

plt.tight_layout()
plt.show()



print(f"\n{'Year':<6} {'Qb':>12} {'Qp':>12} {'Volume':>12} {'Salinity':>12}")
print("-"*65)

for i, year in enumerate(future_years):
    print(f"{year:<6} "
          f"{forecast_qb[i]:>12.3e} "
          f"{forecast_qp[i]:>12.3e} "
          f"{forecast_V[i]:>12.3e} "
          f"{forecast_S[i]:>12.3f}")